# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/example/example.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/example/example.proto',
  package='grpc.srv.example',
  syntax='proto3',
  serialized_pb=_b('\n\x1bproto/example/example.proto\x12\x10grpc.srv.example\x1a\x1cgoogle/api/annotations.proto\"\x16\n\x07Message\x12\x0b\n\x03say\x18\x01 \x01(\t\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x08Response\x12\x0b\n\x03msg\x18\x01 \x01(\t\"!\n\x10StreamingRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\"\"\n\x11StreamingResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\"\x16\n\x04Ping\x12\x0e\n\x06stroke\x18\x01 \x01(\x03\"\x16\n\x04Pong\x12\x0e\n\x06stroke\x18\x01 \x01(\x03\x32\x65\n\x07\x45xample\x12Z\n\x04\x43\x61ll\x12\x19.grpc.srv.example.Request\x1a\x1a.grpc.srv.example.Response\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/v1/example/call:\x01*b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='grpc.srv.example.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='say', full_name='grpc.srv.example.Message.say', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=101,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='grpc.srv.example.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpc.srv.example.Request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=126,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='grpc.srv.example.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='grpc.srv.example.Response.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=151,
)


_STREAMINGREQUEST = _descriptor.Descriptor(
  name='StreamingRequest',
  full_name='grpc.srv.example.StreamingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='grpc.srv.example.StreamingRequest.count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=186,
)


_STREAMINGRESPONSE = _descriptor.Descriptor(
  name='StreamingResponse',
  full_name='grpc.srv.example.StreamingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='grpc.srv.example.StreamingResponse.count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=222,
)


_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='grpc.srv.example.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stroke', full_name='grpc.srv.example.Ping.stroke', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=246,
)


_PONG = _descriptor.Descriptor(
  name='Pong',
  full_name='grpc.srv.example.Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stroke', full_name='grpc.srv.example.Pong.stroke', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=270,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['StreamingRequest'] = _STREAMINGREQUEST
DESCRIPTOR.message_types_by_name['StreamingResponse'] = _STREAMINGRESPONSE
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'proto.example.example_pb2'
  # @@protoc_insertion_point(class_scope:grpc.srv.example.Message)
  ))
_sym_db.RegisterMessage(Message)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'proto.example.example_pb2'
  # @@protoc_insertion_point(class_scope:grpc.srv.example.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'proto.example.example_pb2'
  # @@protoc_insertion_point(class_scope:grpc.srv.example.Response)
  ))
_sym_db.RegisterMessage(Response)

StreamingRequest = _reflection.GeneratedProtocolMessageType('StreamingRequest', (_message.Message,), dict(
  DESCRIPTOR = _STREAMINGREQUEST,
  __module__ = 'proto.example.example_pb2'
  # @@protoc_insertion_point(class_scope:grpc.srv.example.StreamingRequest)
  ))
_sym_db.RegisterMessage(StreamingRequest)

StreamingResponse = _reflection.GeneratedProtocolMessageType('StreamingResponse', (_message.Message,), dict(
  DESCRIPTOR = _STREAMINGRESPONSE,
  __module__ = 'proto.example.example_pb2'
  # @@protoc_insertion_point(class_scope:grpc.srv.example.StreamingResponse)
  ))
_sym_db.RegisterMessage(StreamingResponse)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), dict(
  DESCRIPTOR = _PING,
  __module__ = 'proto.example.example_pb2'
  # @@protoc_insertion_point(class_scope:grpc.srv.example.Ping)
  ))
_sym_db.RegisterMessage(Ping)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), dict(
  DESCRIPTOR = _PONG,
  __module__ = 'proto.example.example_pb2'
  # @@protoc_insertion_point(class_scope:grpc.srv.example.Pong)
  ))
_sym_db.RegisterMessage(Pong)



_EXAMPLE = _descriptor.ServiceDescriptor(
  name='Example',
  full_name='grpc.srv.example.Example',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=272,
  serialized_end=373,
  methods=[
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='grpc.srv.example.Example.Call',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\025\"\020/v1/example/call:\001*')),
  ),
])
_sym_db.RegisterServiceDescriptor(_EXAMPLE)

DESCRIPTOR.services_by_name['Example'] = _EXAMPLE

# @@protoc_insertion_point(module_scope)
